# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish

on:
  release:
    types: [created]

jobs:
  build_test_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '.yarn/cache'
          key: ${{ hashFiles('yarn.lock') }}
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: yarn config set npmRegistries --json '{"https://registry.yarnpkg.com":{"npmAuthToken":"${NODE_AUTH_TOKEN}","npmAlwaysAuth":true}}'
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - run: yarn npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
